
# TODO Do not edit this file directly! Instead, create a new file called
# TODO a03_username.py and copy this code into it!

#################################################################################
# Author:
# Username:
#
# Assignment:
# Purpose:
# Google Doc Link:
#
#################################################################################
# Acknowledgements:
#
#
#################################################################################

import turtle


def octagon(t, length, pensize, color, ):
        t.penup()
        t.setpos(-100, 175)
        t.pensize(pensize)
        t.color(color)
        t.pendown()
        # Creates the sides of the square
        for i in range(4):
            t.forward(length)
            t.right(90)
            t.left(30)





 def octagon(t, length, pensize, color ):
    t.penup()
    t.setpos(-76, 150)
    t.pensize(pensize)
    t.color(color)
    t.pendown()
    for i in range(4):
        t.forward(50)
        t.right(45)

    def main():  # Define the main function
        wn = turtle.Screen()  # Set up the window and its attributes
        wn.bgcolor("yellow")
        wn.exitonclick()

    main()  # Invoke the main function

    """
    Docstring for function_1
    """
    pass
    # ....


def function_2():
    def draw_octagon():
        for i in range(8):
            t.forward(50)
            t.right(45)
            draw_octagon()
    """
    Docstring for function_2
    """
    pass
    # ...
def main()
    wn = turtle.Screen()
    square_turtle = turtle.Turtle()
    octagon_turtle = turtle.Turtle()
    octagon_turtle.speed(10)
    octagon(square_turtle, 500, 25, "blue")
    octagon(octagon_turtle, 452, 25, "red")
    wn.exitonclick()
    """
    Docstring for main
    """
    # ...
    def octagon()
    def
    # Function call to function_1
    function_2()            # Function call to function_2


main()


