
# TODO Do not edit this file directly! Instead, create a new file called
# TODO a03_username.py and copy this code into it!

#################################################################################
# Author: Natinael
# Username: abeben
#
# Assignment:
# Purpose: craete shapes
# Google Doc Link: https://docs.google.com/document/d/1oCgUUzPUkJmjpkR1ORs79UrL4MShpz9oqyJy_pKO4vk/edit?usp=sharing
#
#################################################################################
# Acknowledgements:
#
#
#################################################################################

import turtle


def square(t, length, pensize, color):
    t.penup()
    t.setpos(-100, 175)
    t.pensize(pensize)
    t.color(color)
    t.pendown()
    for i in range(8):
        t.forward(100)
        t.right(90)

    """
    Docstring for function_1
    
    print (creates square _doc_)
    """
    pass
    # ....

    def draw_square():
        for i in range(8):
            t.forward(100)
            t.right(90)

    t.right(-90)
    t.penup()
    t.forward(50)
    t.right(-90)
    t.forward(200)
    t.pendown()
    draw_square()
    """
    Docstring for function_2
    """

    pass
    # ...


def main():
    wn = turtle.Screen()
    square_turtle = turtle.Turtle()
    square_turtle = turtle.Turtle()
    square_turtle.speed(10)
    square(square_turtle, 400, 25, "green")
    square(square_turtle, 452, 25, "red")
    wn.exitonclick()
    """
    Docstring for main
    print( for turtle _doc_)
    """
    # ...
    def square():            # Function call to function_1
    def drawsquare()         # Function call to function_2


main()


